services:
  frontend:
    build:
      context: frontend
    env_file:
      - frontend/.env
    volumes:
      - frontend:/app/frontend/dist
    ports:
      - "5173:5173"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    networks:
      - internal

  backend:
    restart: always
    build:
      context: backend
    env_file:
      - backend/.env
    volumes:
      - ./backend/src:/app/src
      - ./backend/public/temp:/app/src/public/temp
      - ./backend/public/uploads:/app/src/public/uploads
      - backend_images:/app/src/public/images
    ports:
      - 3000:3000
    networks:
      - internal
    depends_on:
      - mongo

  server:
    build:
      context: nginx
    ports:
      - 80:80
    volumes:
      - frontend:/var/app
      - ./backend/public:/app/src/public
    depends_on:
      - frontend
      - backend
    networks:
      - internal

volumes:
  frontend:
  backend_images:
  # public:
  db:

networks:
  internal:
